### ISSUE TITLE
how to save data to file?

### ISSUE THREAD

**Issue by vinnitu** [Akagi201/curl-rtsp#1]
after handshake how to get raw data from stream?

**Comment by Haffon** [comment]
Hi vinnitu, you can set the debug callback function to retrieve the raw data.
curl_easy_setopt(CURL *handle, CURLOPT_DEBUGFUNCTION,  debug_callback)
here is the explanation and sample code: https://curl.haxx.se/libcurl/c/CURLOPT_DEBUGFUNCTION.html
